name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - vim
  - nodejs
  - upsetplot
  - seaborn
  - git
  - python
  - pybedtools
  - bedtools
  - xclip
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - pip
  - ipython
  - pandas==2.3.3
  - numpy==2.3.5
  - matplotlib
  - scipy
  - ipykernel
  - adjusttext
  - scikit-learn
  - pyhpo
  - pyliftover
  - pip:
    - gwplot @ https://files.pythonhosted.org/packages/e1/7c/5be79230eb84b4533b647598cf9306dc77d520cb07d3d49263fd1269072a/gwplot-0.4.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
